name = "CedarPublic"
uuid = "d5383f58-d01c-4af7-9150-c3deb6df5400"
repo = "https://github.com/CedarEDA/PublicRegistry.git"
description = "CedarEDA public package registry"

[packages]
097a23ca-5f42-4755-97f7-1452623ac32d = { name = "CedarEDA", path = "C/CedarEDA" }
32805668-c3d0-42c2-aafd-0d0a9857a104 = { name = "DAECompiler", path = "D/DAECompiler" }
361f1f8b-9353-4122-8fb9-15bd988babab = { name = "CedarWaves", path = "C/CedarWaves" }
3a9dc963-4db1-4336-a55a-41e26ba2a676 = { name = "Sky130PDK", path = "S/Sky130PDK" }
4c528db8-839e-4d0b-8de9-a61e03c09612 = { name = "GF180MCUPDK", path = "G/GF180MCUPDK" }
5f726cbb-fb92-4cd0-9fae-dbb64c46e42b = { name = "ASAP7PDK", path = "A/ASAP7PDK" }
64909d44-ed92-46a8-bbd9-f047dfbdc84b = { name = "StateSelection", path = "S/StateSelection" }
72c5b8b4-6eac-4a9c-9647-0f5a982ce801 = { name = "SpectreNetlistParser", path = "S/SpectreNetlistParser" }
8fc43420-9e17-4e89-a998-f4e9593a1dfc = { name = "Lexers", path = "L/Lexers" }
9075980a-f0c7-46d2-945a-cc5bead5ad4a = { name = "CedarSim", path = "C/CedarSim" }
b333aca1-b97d-47c9-9908-8e5a8c115e58 = { name = "VerilogAParser", path = "V/VerilogAParser" }
db13d295-e716-48aa-bdca-f6cce3d4ecc6 = { name = "CMC", path = "C/CMC" }
fa7570ea-a14f-11ec-018e-d96f3217f940 = { name = "BSIM4", path = "B/BSIM4" }
